# Churn Modelling

# Artificial Neural Network

## Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.8.0'

## Data preprocessing

     Importing the dataset

In [49]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [50]:

print(x)
print(x.shape)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
(10000, 10)


In [51]:

print(y)
print(y.shape)

[1 0 1 ... 1 1 0]
(10000,)


Encoding Categorical Data

Label Encoding the "Gender" column

In [52]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:, 2])

In [53]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
# Female = 0
# Male = 1

One hot encoding the "Geography" column

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [55]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [17]:
# France is encoded to 1.0 0.0 0.0
# Spain is encoded to 0.0 0.0 1.0
# Germany is encoded to 0.0 1.0 0.0

In [56]:
print(x.shape)

(10000, 12)


In [57]:
print(y.shape)

(10000,)


Splitting the dataset into the Training set and Test set

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

Feature Scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [60]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [61]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


In [62]:
print(y_test)

[0 1 0 ... 0 0 0]


Building the ANN

  Initializing the ANN

In [63]:
ann = tf.keras.models.Sequential()

Adding the input and the first hidden layer

In [64]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
#Dense is used to get a fully connected layer
#First parameter(Units) = no. of neurons : No rule of thumb on how to select the no. of neurons
#Second parameter(Activation Function) = rectifier activation function

Adding the second hidden layer

In [65]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the output layer

In [66]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))
#Sigmoid activation function gives us the probability as well

Training the ANN

Compiling the ANN

In [73]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = ['accuracy'])
#adam optimizer helps perform stochastic gradient descent
#For binary, the loss must be binary cross entropy and for non-binary, the loss must be categorical cross entropy
#When performing non-binary while predicting for multi-class = softmax

Training the ANN on the training set

In [74]:
ann.fit(x = x_train,y = y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7950
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4604 - accuracy: 0.8060
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4365 - accuracy: 0.8104
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4273 - accuracy: 0.8174
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4215 - accuracy: 0.8220
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4173 - accuracy: 0.8266
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4143 - accuracy: 0.8271
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8299
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8296
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4072 - accura

Making the predictions and evaluating the model

In [75]:
prediction = ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

print(prediction)
#Prediction = Chances of person leaving bank

[[0.03814283]]


In [77]:
if(prediction > 0.5):
  print("Person is highly likely to leave the bank")
else:
  print("Person is not likely to leave the bank")

Person is not likely to leave the bank


Predicting the test set results

In [78]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the confusion matrix

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1519   76]
 [ 201  204]]


0.8615